# Generated by Django 5.0.2 on 2024-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('skitka', models.CharField(max_length=100)),
            ],
        ),
    ]
