# Generated by Django 5.0.2 on 2024-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='cost',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
