# Generated by Django 5.0.2 on 2024-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AlterField(
            model_name='expesiv',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gadjet',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='texnika',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
