# Generated by Django 5.0.2 on 2024-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_expesiv_skitka_alter_gadjet_skitka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expesiv',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gadjet',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='texnika',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='skitka',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
