# Generated by Django 5.0.4 on 2024-06-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_expesiv_skitka_alter_gadjet_skitka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tovar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='skitka',
            field=models.BooleanField(default=False),
        ),
    ]
