# Generated by Django 5.0.6 on 2024-06-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_cart_tovar_alter_tovar_skitka'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gadjet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet'),
        ),
    ]
