# Generated by Django 5.0.6 on 2024-06-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_cart_gadjet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook'),
        ),
    ]
