# Generated by Django 5.0.6 on 2024-06-15 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_gadjet__unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadjet',
            name='_unique_id',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Field must contain at least 1 letter, 1 number, and 1 symbol except ? & ^.%*', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
    ]
