# Generated by Django 5.0.6 on 2024-06-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_gadjet__unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadjet',
            old_name='_unique_id',
            new_name='unique_id',
        ),
    ]
