# Generated by Django 5.0.6 on 2024-06-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_texnika_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='texnika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika'),
        ),
    ]
