# Generated by Django 5.0.6 on 2024-06-15 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_cart_texnika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadjet',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
    ]
