# Generated by Django 5.0.6 on 2024-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_gadjet_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
