# Generated by Django 5.0.6 on 2024-07-02 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_thumbsup_delete_like_tovar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbsup',
            options={'verbose_name': 'Like bosilganlar', 'verbose_name_plural': 'Like bosilganlar'},
        ),
        migrations.AddField(
            model_name='cart',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
        migrations.AddField(
            model_name='expesiv',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
        migrations.AddField(
            model_name='kitob',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
        migrations.AddField(
            model_name='notebook',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
        migrations.AddField(
            model_name='tv',
            name='unique_id',
            field=models.CharField(blank=True, help_text="Bu yerda faqat 90ta lik random string, number va symboldan iborat bo'ladi va siz buni yaratishiz shart emas, dastur o'zi yaratib beradi", max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='Bu symbollardan tashqari ?&^', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')]),
        ),
    ]
