# Generated by Django 5.0.6 on 2024-07-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_smm'),
    ]

    operations = [
        migrations.AddField(
            model_name='smm',
            name='expesive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.expesiv'),
        ),
        migrations.AddField(
            model_name='smm',
            name='gadjet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet'),
        ),
        migrations.AddField(
            model_name='smm',
            name='kitob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kitob'),
        ),
        migrations.AddField(
            model_name='smm',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook'),
        ),
        migrations.AddField(
            model_name='smm',
            name='texnika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika'),
        ),
        migrations.AddField(
            model_name='smm',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='smm',
            name='tovar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar'),
        ),
        migrations.AddField(
            model_name='smm',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tv'),
        ),
    ]
